import { mkdir, rm, unlink } from "node:fs/promises";
import { $ } from "bun";

const GENERATED_FILES = [
	"src/_web-assets.generated.ts",
	"src/_skill-files.generated.ts",
];

const TARGETS = [
	{ target: "bun-linux-x64", output: "openmantis-linux-x64" },
	{ target: "bun-linux-arm64", output: "openmantis-linux-arm64" },
	{ target: "bun-darwin-x64", output: "openmantis-darwin-x64" },
	{ target: "bun-darwin-arm64", output: "openmantis-darwin-arm64" },
	{ target: "bun-windows-x64", output: "openmantis-windows-x64.exe" },
	{ target: "bun-windows-arm64", output: "openmantis-windows-arm64.exe" },
] as const;

async function buildWeb() {
	console.log("Building web frontend...");
	await $`bun run build:web`;
	console.log("Web frontend built.");
}

async function collectFiles(patterns: string[]): Promise<string[]> {
	const files: string[] = [];
	for (const pattern of patterns) {
		const glob = new Bun.Glob(pattern);
		for await (const path of glob.scan({ dot: true })) {
			files.push(path);
		}
	}
	return files;
}

/**
 * Generate a TS module that imports files using `with { type: "file" }`.
 * This is the ONLY way to get files into Bun.embeddedFiles in a compiled binary.
 * CLI arguments to bun build --compile do NOT populate Bun.embeddedFiles.
 */
async function generateEmbedModules(): Promise<void> {
	// Web assets
	const webFiles = await collectFiles(["dist/web/**/*"]);
	{
		const imports: string[] = [];
		const entries: string[] = [];

		for (let i = 0; i < webFiles.length; i++) {
			const filePath = webFiles[i]!;
			const webIdx = filePath.indexOf("dist/web/");
			const relativePath = filePath.slice(webIdx + "dist/web/".length);

			imports.push(`import a${i} from "../${filePath}" with { type: "file" };`);
			entries.push(`\t${JSON.stringify(relativePath)}: a${i},`);
		}

		const content = `// Auto-generated by scripts/build.ts — do not edit
${imports.join("\n")}

export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;
		await Bun.write("src/_web-assets.generated.ts", content);
		console.log(`Generated web assets module (${webFiles.length} files)`);
	}

	// Skill files
	const skillFiles = await collectFiles(["skills/builtin/**/*"]);
	{
		const imports: string[] = [];
		const entries: string[] = [];

		for (let i = 0; i < skillFiles.length; i++) {
			const filePath = skillFiles[i]!;
			const skillIdx = filePath.indexOf("skills/builtin/");
			const relativePath = filePath.slice(skillIdx);

			imports.push(`import s${i} from "../${filePath}" with { type: "file" };`);
			entries.push(`\t${JSON.stringify(relativePath)}: s${i},`);
		}

		const content = `// Auto-generated by scripts/build.ts — do not edit
${imports.join("\n")}

export const SKILL_FILES: Record<string, string> = {
${entries.join("\n")}
};
`;
		await Bun.write("src/_skill-files.generated.ts", content);
		console.log(`Generated skill files module (${skillFiles.length} files)`);
	}
}

async function signDarwin(outfile: string, targetName: string): Promise<void> {
	if (process.platform !== "darwin") {
		console.warn(
			`⚠️  Skipping codesign for ${targetName}: not running on macOS. ` +
				"The binary will likely fail to launch on macOS (killed by Gatekeeper/kernel). " +
				"Build darwin targets on a macOS runner.",
		);
		return;
	}

	const entitlements = "scripts/entitlements.plist";

	// `bun build --compile` leaves a pre-embedded signature blob that
	// `codesign` refuses to overwrite ("invalid or unsupported format for
	// signature"). Strip it first, then apply an ad-hoc signature with the
	// JIT entitlements Bun requires to run on macOS.
	const remove = Bun.spawn(
		["codesign", "--remove-signature", outfile],
		{ stdio: ["inherit", "inherit", "inherit"] },
	);
	if ((await remove.exited) !== 0) {
		throw new Error("codesign --remove-signature failed");
	}

	console.log(`Ad-hoc signing ${outfile} with JIT entitlements...`);
	const proc = Bun.spawn(
		[
			"codesign",
			"--sign",
			"-",
			"--force",
			"--timestamp=none",
			"--entitlements",
			entitlements,
			outfile,
		],
		{ stdio: ["inherit", "inherit", "inherit"] },
	);
	const exitCode = await proc.exited;
	if (exitCode !== 0) {
		throw new Error(`codesign failed with exit code ${exitCode}`);
	}
}

async function compile(target?: string) {
	const targets = target
		? TARGETS.filter((t) => t.target === target)
		: [undefined]; // current platform

	if (target && targets.length === 0) {
		console.error(`Unknown target: ${target}`);
		console.error(`Available: ${TARGETS.map((t) => t.target).join(", ")}`);
		process.exit(1);
	}

	for (const t of targets) {
		const outfile = t ? `dist/bin/${t.output}` : "dist/bin/openmantis";
		const args: string[] = [
			"bun",
			"build",
			"--compile",
			"--minify",
			"--sourcemap",
		];
		if (t) {
			args.push("--target", t.target);
		}
		args.push("--outfile", outfile, "./src/cli.ts");

		console.log(`Compiling${t ? ` for ${t.target}` : ""}...`);

		const proc = Bun.spawn(args, { stdio: ["inherit", "inherit", "inherit"] });
		const exitCode = await proc.exited;
		if (exitCode !== 0) {
			throw new Error(`Compilation failed with exit code ${exitCode}`);
		}

		console.log(`Built: ${outfile}`);

		const isDarwin = t
			? t.target.startsWith("bun-darwin-")
			: process.platform === "darwin";
		if (isDarwin) {
			await signDarwin(outfile, t?.target ?? "current platform");
		}
	}
}

async function main() {
	const args = process.argv.slice(2);
	const targets: string[] = [];
	for (let i = 0; i < args.length; i++) {
		if (args[i] === "--target" && args[i + 1]) {
			targets.push(args[i + 1]!);
			i++;
		}
	}
	const all = args.includes("--all");

	await rm("dist", { recursive: true, force: true });
	await buildWeb();
	await generateEmbedModules();
	await mkdir("dist/bin", { recursive: true });

	try {
		if (all) {
			for (const t of TARGETS) {
				await compile(t.target);
			}
		} else if (targets.length > 0) {
			for (const t of targets) {
				await compile(t);
			}
		} else {
			await compile();
		}
	} finally {
		// Clean up generated files to avoid typecheck issues
		for (const f of GENERATED_FILES) {
			try {
				await unlink(f);
			} catch {}
		}
	}
}

main().catch((err) => {
	console.error("Build failed:", err);
	process.exit(1);
});
