import { mkdir, unlink } from "node:fs/promises";
import { $ } from "bun";

const GENERATED_FILES = [
	"src/_web-assets.generated.ts",
	"src/_skill-files.generated.ts",
];

const TARGETS = [
	{ target: "bun-linux-x64", output: "openmantis-linux-x64" },
	{ target: "bun-linux-arm64", output: "openmantis-linux-arm64" },
	{ target: "bun-darwin-x64", output: "openmantis-darwin-x64" },
	{ target: "bun-darwin-arm64", output: "openmantis-darwin-arm64" },
	{ target: "bun-windows-x64", output: "openmantis-windows-x64.exe" },
	{ target: "bun-windows-arm64", output: "openmantis-windows-arm64.exe" },
] as const;

async function buildWeb() {
	console.log("Building web frontend...");
	await $`bun run build:web`;
	console.log("Web frontend built.");
}

async function collectFiles(patterns: string[]): Promise<string[]> {
	const files: string[] = [];
	for (const pattern of patterns) {
		const glob = new Bun.Glob(pattern);
		for await (const path of glob.scan({ dot: true })) {
			files.push(path);
		}
	}
	return files;
}

/**
 * Generate a TS module that imports files using `with { type: "file" }`.
 * This is the ONLY way to get files into Bun.embeddedFiles in a compiled binary.
 * CLI arguments to bun build --compile do NOT populate Bun.embeddedFiles.
 */
async function generateEmbedModules(): Promise<void> {
	// Web assets
	const webFiles = await collectFiles(["dist/web/**/*"]);
	{
		const imports: string[] = [];
		const entries: string[] = [];

		for (let i = 0; i < webFiles.length; i++) {
			const filePath = webFiles[i]!;
			const webIdx = filePath.indexOf("dist/web/");
			const relativePath = filePath.slice(webIdx + "dist/web/".length);

			imports.push(`import a${i} from "../${filePath}" with { type: "file" };`);
			entries.push(`\t${JSON.stringify(relativePath)}: a${i},`);
		}

		const content = `// Auto-generated by scripts/build.ts — do not edit
${imports.join("\n")}

export const WEB_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;
		await Bun.write("src/_web-assets.generated.ts", content);
		console.log(`Generated web assets module (${webFiles.length} files)`);
	}

	// Skill files
	const skillFiles = await collectFiles(["skills/builtin/**/*"]);
	{
		const imports: string[] = [];
		const entries: string[] = [];

		for (let i = 0; i < skillFiles.length; i++) {
			const filePath = skillFiles[i]!;
			const skillIdx = filePath.indexOf("skills/builtin/");
			const relativePath = filePath.slice(skillIdx);

			imports.push(`import s${i} from "../${filePath}" with { type: "file" };`);
			entries.push(`\t${JSON.stringify(relativePath)}: s${i},`);
		}

		const content = `// Auto-generated by scripts/build.ts — do not edit
${imports.join("\n")}

export const SKILL_FILES: Record<string, string> = {
${entries.join("\n")}
};
`;
		await Bun.write("src/_skill-files.generated.ts", content);
		console.log(`Generated skill files module (${skillFiles.length} files)`);
	}
}

async function compile(target?: string) {
	const targets = target
		? TARGETS.filter((t) => t.target === target)
		: [undefined]; // current platform

	if (target && targets.length === 0) {
		console.error(`Unknown target: ${target}`);
		console.error(`Available: ${TARGETS.map((t) => t.target).join(", ")}`);
		process.exit(1);
	}

	for (const t of targets) {
		const outfile = t ? `dist/bin/${t.output}` : "dist/bin/openmantis";
		const args: string[] = [
			"bun",
			"build",
			"--compile",
			"--minify",
			"--sourcemap",
		];
		if (t) {
			args.push("--target", t.target);
		}
		args.push("--outfile", outfile, "./src/cli.ts");

		console.log(`Compiling${t ? ` for ${t.target}` : ""}...`);

		const proc = Bun.spawn(args, { stdio: ["inherit", "inherit", "inherit"] });
		const exitCode = await proc.exited;
		if (exitCode !== 0) {
			throw new Error(`Compilation failed with exit code ${exitCode}`);
		}

		console.log(`Built: ${outfile}`);
	}
}

async function main() {
	const args = process.argv.slice(2);
	const targetFlag = args.indexOf("--target");
	const target = targetFlag !== -1 ? args[targetFlag + 1] : undefined;
	const all = args.includes("--all");

	await buildWeb();
	await generateEmbedModules();
	await mkdir("dist/bin", { recursive: true });

	try {
		if (all) {
			for (const t of TARGETS) {
				await compile(t.target);
			}
		} else {
			await compile(target);
		}
	} finally {
		// Clean up generated files to avoid typecheck issues
		for (const f of GENERATED_FILES) {
			try {
				await unlink(f);
			} catch {}
		}
	}
}

main().catch((err) => {
	console.error("Build failed:", err);
	process.exit(1);
});
